### PR TITLE
support option for auto install and install of package manager in autolibs flag

### LINKED ISSUE #107: autolibs option does not support 3, 4
Mode 3 (packages) and 4 (enable) are not supported by this gem. https://rvm.io/rvm/autolibs

### PR DESCRIPTION
**Pull request by billywatson**
fixes #107

### CODE REVIEW

**Comment by billywatson** [comment]
okay finally got the tests passing, @mpapis

**Comment by mpapis** [comment]
`4 enable enabled` should not be on the list, as the variable says `autolibs_flag_no_requirements` - it's meant to be activated when requirements are limited (poor choice of wording on my side), there might be a conflict between those two lines:

- https://github.com/billywatson/rvm-capistrano/commit/f3e1be841343e0179c0f929649335d8675d7bab1#diff-1ef9f274f5732fa3a2c996beb7c90416L45
- https://github.com/billywatson/rvm-capistrano/commit/f3e1be841343e0179c0f929649335d8675d7bab1#diff-1ef9f274f5732fa3a2c996beb7c90416L51

I guess the second one could be removed ... although I'm not fully sure, try removing the `4 enable enabled` and `autolibs_flag = "1" unless autolibs_flag_no_requirements` - and try testing it

**Comment by billywatson** [comment]
That check is there to make sure that the option passed in is valid. It's actually the check that originally caused me to find this code in the first place. I was trying to pass in '3' and it wouldn't let me.

Also, I've already used my branch to install RVM so it's totally working.

**Comment by billywatson** [comment]
I can add some more automated tests for the check, if you want. I'm not really clear on what you're wanting, though.

**Comment by mpapis** [comment]
you are getting closer, the `3` and `4` require `sudo` and it's handled in `https://github.com/billywatson/rvm-capistrano/blob/bump_autolibs_flag/lib/rvm/capistrano/install_ruby.rb#L55-L58` - adding `3` makes it continue without extra `sudo` invocation - which will work in rare occasions (`root` user, some systems that do not require `UID` `0` - like OSX)

**Comment by mpapis** [comment]
after rechecking `3` should not be on the list, this list is only meant for options that do not require `sudo` - anything else (`3` and `4`) require `sudo`

**Comment by mpapis** [comment]
if you want to add validation list - it should be separate list

**Comment by billywatson** [comment]
Well I don't really care about the validation list, I just thought that's what the list was. 

From what you're telling me, I think this:

```
autolibs_flag = "1" unless autolibs_flag_no_requirements

install_ruby_threads = fetch(:rvm_install_ruby_threads,nil).nil? ? '' : "-j #{rvm_install_ruby_threads}"
unless autolibs_flag_no_requirements
  command_install << "#{rvm_if_sudo} #{path_to_bin_rvm} --autolibs=#{autolibs_flag} requirements #{ruby}"
  command_install << "; "
end
command_install << with_rvm_group("#{path_to_bin_rvm} --autolibs=#{autolibs_flag} #{rvm_install_ruby} #{ruby} #{install_ruby_threads} #{rvm_install_ruby_params}", :subject_class => :rubies)
```

could be changed to something like this:

```
install_ruby_threads = fetch(:rvm_install_ruby_threads,nil).nil? ? '' : "-j #{rvm_install_ruby_threads}"
unless autolibs_flag_no_requirements
  command_install << "#{rvm_if_sudo} #{path_to_bin_rvm} --autolibs=#{autolibs_flag} requirements #{ruby}"
  command_install << "; "
end
command_install << with_rvm_group("#{path_to_bin_rvm} --autolibs=#{autolibs_flag || '1'} #{rvm_install_ruby} #{ruby} #{install_ruby_threads} #{rvm_install_ruby_params}", :subject_class => :rubies)
```


Is that going down the right track?

**Comment by billywatson** [comment]
BTW, I've changed the autolibs in the second command_install line to be `autolibs=#{autolibs_flag || '1'}` instead of overriding it before the unless block, in case that wasn't clear

**Comment by mpapis** [comment]
can you revert all changes and just remove `autolibs_flag = "1" unless autolibs_flag_no_requirements`? - it looks like the right thing to do now

**Comment by billywatson** [comment]
okay

**Comment by billywatson** [comment]
The only other change I kept now was getting those other specs that were failing to pass.

**Comment by mpapis** [comment]
last unneeded change is https://github.com/wayneeseguin/rvm-capistrano/pull/108/files#diff-1ef9f274f5732fa3a2c996beb7c90416L47 - it's just formatting, can you please revert this part?

**Comment by billywatson** [comment]
oops, sure

**Comment by billywatson** [comment]
done

**Comment by mpapis** [comment]
now does it require new version?

**Comment by billywatson** [comment]
bundle update rspec should do it. It wasn't locked and probably should be. I can work on that next, if you want.

**Comment by mpapis** [comment]
yes could you please open a PR for this and then I can push new version

**Comment by billywatson** [comment]
wait, a little confused. Are you wanting me to bump the version of rvm-capistrano or lock the version of rspec? Both probably need to be done, actually.

**Comment by mpapis** [comment]
and `1.5.6` released, I have asked @wayneeseguin to add you to the team on rvm-capistrano :)

**Comment by billywatson** [comment]
okay thanks. I'd be happy to work on it more often.

**Comment by mpapis** [comment]
just open a PR anytime you feel something needs fixing / improving :)

**Comment by billywatson** [comment]
Certainly. Thanks!

**Pull request merged**
